tap "homebrew/bundle"
tap "homebrew/services"
tap "homeport/tap"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
brew "aichat"
brew "libpng"
brew "libtiff"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "asdf"
brew "boost"
brew "avrdude"
brew "glib"
brew "cairo"
brew "cmake"
brew "cryptography"
brew "dua-cli"
brew "libidn2"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "leptonica"
brew "libass"
brew "libsndfile"
brew "tesseract"
brew "gd"
brew "git"
brew "hyperfine"
brew "jrnl"
brew "libraqm"
brew "mad"
brew "pillow"
brew "python@3.11"
brew "ripgrep"
brew "scc"
brew "starship"
brew "streamrip"
brew "tcl-tk"
brew "trash", link: true
brew "zlib"
brew "zoxide"
brew "qmk/qmk/qmk"
cask "flux-app", args: { appdir: "/Applications" }
cask "font-iosevka-term-nerd-font"
cask "font-office-code-pro"
cask "ghostty"
cask "karabiner-elements", args: { appdir: "/Applications" }
cask "keka", args: { appdir: "/Applications" }
cask "raycast"
cask "tower", args: { appdir: "/Applications" }
