format = """
$directory\
${custom.git_dirty}\
$git_status\
$fill\
$time\
$line_break\
$character"""

add_newline = true

[fill]
symbol = ' '

[directory]
style = "bright-white bold"

[time]
disabled = false
format = '[$time]($style) '
time_format = '%a %d.%m %H:%M'
style = 'white'

[character]
success_symbol = "[](bright-white)"
error_symbol = "[](bright-red)"

[git_status]
format = '([$ahead_behind]($style) )'
ahead = '[ ](green)'
behind = '[ ](red)'
diverged = '[ ](red)'

[custom.git_dirty]
require_repo = true
shell = ['sh']
when = 'test -n "$(git status --porcelain)"'
format = '[ ](yellow)'
