format = """
$directory\
$git_status\
$fill\
$time\
$line_break\
$character"""

add_newline = true

[fill]
symbol = ' '

[directory]
style = "bright-white bold"

[time]
disabled = false
format = '[$time]($style) '
time_format = '%a %d.%m %H:%M'
style = 'white'

[character]
success_symbol = "[](bright-white)"
error_symbol = "[](bright-red)"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = 'yellow'
ahead = '[ ](green)'
behind = '[ ](red)'
diverged = '[ ](red)'
modified = ' '
renamed = ' '
deleted = ' '
untracked = ' '
staged = ' '
