if vim.g.colors_name then
    vim.cmd("hi clear")
end

vim.g.colors_name = "balamb"
vim.opt.background = "light"

local function set_hl(name, style)
    vim.api.nvim_set_hl(0, name, style)
end

local set_js_hl = function(name, style)
    set_hl(name .. ".jsx", style)
    set_hl(name .. ".tsx", style)
    set_hl(name .. ".javascript", style)
    set_hl(name .. ".typescript", style)
    set_hl(name .. ".javascriptreact", style)
    set_hl(name .. ".typescriptreact", style)
end

set_hl("@attribute.css", { fg = "#d9730d" })
set_hl("@boolean", { fg = "#d9730d" })
set_hl("@character", { fg = "#448361" })
set_hl("@character.special", { fg = "#9065b0" })
set_hl("@comment", { fg = "#b3b2af" })
set_hl("@comment.todo", { fg = "#d44c48" })
set_hl("@constant", { fg = "#37352f" })
set_hl("@constant.builtin", { fg = "#d9730d" })
set_hl("@constant.builtin.rust", { fg = "#33a999" })
set_hl("@constant.css", { fg = "#cb912f" })
set_hl("@constant.elixir", { fg = "#37352f" })
set_hl("@constructor.python", { fg = "#337ea9" })
set_hl("@function", { fg = "#337ea9" })
set_hl("@function.builtin", { fg = "#337ea9" })
set_hl("@function.macro", { fg = "#337ea9" })
set_hl("@keyword", { fg = "#9065b0" })
set_hl("@keyword.directive.markdown", { fg = "#9065b0" })
set_hl("@label.javascript", { fg = "#9065b0" })
set_hl("@label.markdown", { fg = "#37352f" })
set_hl("@label.ruby", { fg = "#b3b2af" })
set_hl("@label.yaml", { fg = "#37352f" })
set_hl("@markup.heading", { fg = "#337ea9" })
set_hl("@markup.heading.1.html", { fg = "#37352f" })
set_hl("@markup.heading.2.html", { fg = "#37352f" })
set_hl("@markup.heading.3.html", { fg = "#37352f" })
set_hl("@markup.heading.4.html", { fg = "#37352f" })
set_hl("@markup.heading.5.html", { fg = "#37352f" })
set_hl("@markup.heading.6.html", { fg = "#37352f" })
set_hl("@markup.heading.7.html", { fg = "#37352f" })
set_hl("@markup.heading.html", { fg = "#37352f" })
set_hl("@markup.italic.markdown_inline", { fg = "#9065b0", italic = true })
set_hl("@markup.link.label.markdown_inline", { fg = "#337ea9" })
set_hl("@markup.list", { fg = "#a2a19e" })
set_hl("@markup.quote.markdown", { italic = true })
set_hl("@markup.raw.markdown_inline", { fg = "#9065b0" })
set_hl("@markup.strikethrough.markdown_inline", { strikethrough = true })
set_hl("@markup.strong.markdown_inline", { fg = "#9065b0", bold = true })
set_hl("@module.elixir", { fg = "#37352f" })
set_hl("@number", { fg = "#d9730d" })
set_hl("@number.css", { fg = "#d9730d" })
set_hl("@number.float.css", { fg = "#d9730d" })
set_hl("@operator", { fg = "#9065b0" })
set_hl("@property", { fg = "#37352f" })
set_hl("@punctuation", { fg = "#a2a19e" })
set_hl("@punctuation.delimiter.regex", { fg = "#9065b0" })
set_hl("@punctuation.special", { fg = "#9065b0" })
set_hl("@punctuation.special.markdown", { fg = "#a2a19e" })
set_hl("@string", { fg = "#448361" })
set_hl("@string.css", { fg = "#448361" })
set_hl("@string.documentation", { fg = "#b3b2af" })
set_hl("@string.escape", { fg = "#9065b0" })
set_hl("@string.special", { fg = "#9065b0" })
set_hl("@string.special.symbol", { fg = "#37352f" })
set_hl("@string.special.symbol.elixir", { fg = "#37352f" })
set_hl("@tag.attribute", { fg = "#cb912f" })
set_hl("@tag.builtin", { fg = "#9065b0" })
set_hl("@tag.css", { fg = "#9065b0" })
set_hl("@tag.delimiter", { fg = "#a2a19e" })
set_hl("@tag.html", { fg = "#9065b0" })
set_hl("@type", { fg = "#37352f" })
set_hl("@type.builtin", { fg = "#33a999" })
set_hl("@type.css", { fg = "#cb912f" })
set_hl("@type.definition.go", { fg = "#37352f" })
set_hl("@type.prisma", { fg = "#9065b0" })
set_hl("@variable", { fg = "#37352f" })
set_hl("@variable.builtin", { fg = "#9065b0" })
set_hl("@variable.parameter", { fg = "#cb912f" })
set_hl("Character", { link = "String" })
set_hl("CmpItemAbbrMatch", { fg = "#337ea9" })
set_hl("CmpItemAbbrMatchFuzzy", { fg = "#337ea9" })
set_hl("Comment", { fg = "#b3b2af" })
set_hl("Conceal", { fg = "#b3b2af" })
set_hl("Constant", { fg = "#d9730d" })
set_hl("CurSearch", { bg = "#d1cfcc" })
set_hl("CursorLine", { bg = "#e4e3df" })
set_hl("CursorLineNr", { fg = "#5d5c56" })
set_hl("Delimiter", { fg = "#a2a19e" })
set_hl("DiagnosticError", { fg = "#d44c48" })
set_hl("DiagnosticHint", { fg = "#337ea9" })
set_hl("DiagnosticInfo", { fg = "#337ea9" })
set_hl("DiagnosticOk", { fg = "#448361" })
set_hl("DiagnosticUnderlineError", { fg = "#d44c48" })
set_hl("DiagnosticUnderlineWarn", { fg = "#cb912f" })
set_hl("DiagnosticUnnecessary", { fg = "#716f6a" })
set_hl("DiagnosticVirtualTextError", { fg = "#d44c48" })
set_hl("DiagnosticVirtualTextHint", { fg = "#337ea9" })
set_hl("DiagnosticVirtualTextInfo", { fg = "#337ea9" })
set_hl("DiagnosticVirtualTextWarn", { fg = "#cb912f" })
set_hl("DiagnosticWarn", { fg = "#cb912f" })
set_hl("Directory", { fg = "#337ea9" })
set_hl("EgrepifyCol", { fg = "#b3b2af" })
set_hl("EgrepifyLnum", { fg = "#b3b2af" })
set_hl("Error", { fg = "#d44c48" })
set_hl("ErrorMsg", { fg = "#d44c48" })
set_hl("FloatBorder", { fg = "#edece9", bg = "#f7f6f3" })
set_hl("FloatTitle", { fg = "#337ea9", bg = "#f7f6f3" })
set_hl("Function", { fg = "#337ea9" })
set_hl("GitSignsAdd", { fg = "#448361" })
set_hl("GitSignsChange", { fg = "#cb912f" })
set_hl("GitSignsDelete", { fg = "#d44c48" })
set_hl("healthError", { fg = "#d44c48" })
set_hl("healthSuccess", { fg = "#448361" })
set_hl("healthWarning", { fg = "#cb912f" })
set_hl("HydraAmaranth", { fg = "#d9730d" })
set_hl("HydraBlue", { fg = "#337ea9" })
set_hl("HydraPink", { fg = "#9065b0" })
set_hl("HydraRed", { fg = "#d44c48" })
set_hl("HydraTeal", { fg = "#33a999" })
set_hl("Identifier", { fg = "#37352f" })
set_hl("IncSearch", { bg = "#d1cfcc" })
set_hl("Keyword", { fg = "#9065b0" })
set_hl("LineNr", { fg = "#84827d" })
set_hl("LspSignatureActiveParameter", { fg = "#cb912f", bg = "#e4e3df" })
set_hl("MasonHighlight", { fg = "#337ea9" })
set_hl("MasonHighlightBlockBold", { fg = "#f7f6f3", bg = "#337ea9" })
set_hl("MasonMuted", { fg = "#8c8b87" })
set_hl("MasonMutedBlock", { bg = "#e4e3df" })
set_hl("MatchParen", { fg = "NONE" })
set_hl("MiniClueBorder", { fg = "#edece9", bg = "#f7f6f3" })
set_hl("MiniClueDescGroup", { fg = "#cb912f", bg = "#f7f6f3" })
set_hl("MiniClueDescSingle", { fg = "#37352f", bg = "#f7f6f3" })
set_hl("MiniClueNextKey", { fg = "#37352f", bg = "#f7f6f3" })
set_hl("MiniClueNextKeyWithPostkeys", { fg = "#cb912f", bg = "#f7f6f3" })
set_hl("MiniClueSeparator", { fg = "#edece9", bg = "#f7f6f3" })
set_hl("MiniClueTitle", { fg = "#337ea9", bg = "#f7f6f3" })
set_hl("ModeMsg", { fg = "#37352f" })
set_hl("MoreMsg", { fg = "#337ea9" })
set_hl("MsgArea", { fg = "#45443f", bg = "#f7f6f3" })
set_hl("MultiCursor", { link = "Visual" })
set_hl("MultiCursorMain", { link = "Visual" })
set_hl("Normal", { fg = "#37352f", bg = "#f7f6f3" })
set_hl("NormalFloat", { fg = "#37352f", bg = "#f7f6f3" })
set_hl("NormalTerm", { fg = "#45443f", bg = "#f7f6f3" })
set_hl("NvimTreeBookmarkIcon", { fg = "#337ea9" })
set_hl("NvimTreeEmptyFolderName", { fg = "#45443f" })
set_hl("NvimTreeFileIcon", { fg = "#45443f" })
set_hl("NvimTreeFolderIcon", { fg = "#45443f" })
set_hl("NvimTreeFolderName", { fg = "#45443f" })
set_hl("NvimTreeGitDeletedIcon", { fg = "#b5413e" })
set_hl("NvimTreeGitDirtyIcon", { fg = "#ae7c29" })
set_hl("NvimTreeGitIgnoredIcon", { fg = "#8c8b87" })
set_hl("NvimTreeGitMergeIcon", { fg = "#d44c48" })
set_hl("NvimTreeGitNewIcon", { fg = "#3b7053" })
set_hl("NvimTreeGitRenamedIcon", { fg = "#ae7c29" })
set_hl("NvimTreeGitStagedIcon", { fg = "#ae7c29" })
set_hl("NvimTreeImageFile", { fg = "#45443f" })
set_hl("NvimTreeNormal", { fg = "#45443f", bg = "#f7f6f3" })
set_hl("NvimTreeOpenedFolderName", { fg = "#45443f" })
set_hl("NvimTreeRootFolder", { fg = "#337ea9" })
set_hl("NvimTreeSpecialFile", { fg = "#45443f" })
set_hl("NvimTreeStatusLine", { fg = "#45443f", bg = "#f7f6f3", ctermfg = "white" })
set_hl("NvimTreeStatusLineNC", { fg = "#45443f", bg = "#f7f6f3", ctermfg = "black" })
set_hl("NvimTreeWindowPicker", { fg = "#f7f6f3", bg = "#337ea9" })
set_hl("NvimTreeWinSeparator", { fg = "#edece9", bg = "#f7f6f3" })
set_hl("Operator", { link = "Keyword" })
set_hl("Pmenu", { fg = "#45443f", bg = "#f7f6f3" })
set_hl("PmenuSbar", { bg = "#e5e4e1" })
set_hl("PmenuSel", { bg = "#d3d2cf" })
set_hl("PmenuThumb", { bg = "#d3d2cf" })
set_hl("PreProc", { fg = "#337ea9" })
set_hl("Question", { fg = "#337ea9" })
set_hl("Search", { bg = "#e4e3df" })
set_hl("SignColumn", { fg = "#37352f", bg = "#f7f6f3" })
set_hl("Special", { fg = "#9065b0" })
set_hl("Statement", { fg = "#9065b0" })
set_hl("Statement", { link = "Keyword" })
set_hl("StatusLine", { fg = "#45443f", bg = "#f7f6f3", ctermfg = "white" })
set_hl("StatusLineNC", { fg = "#45443f", bg = "#f7f6f3", ctermfg = "black" })
set_hl("String", { fg = "#448361" })
set_hl("Substitute", { fg = "#f7f6f3", bg = "#cb912f" })
set_hl("Tabline", { fg = "#37352f", bg = "#f7f6f3" })
set_hl("TablineFill", { fg = "#f7f6f3", bg = "#f7f6f3" })
set_hl("TablineSel", { fg = "#337ea9", bg = "#f7f6f3" })
set_hl("TelescopeBorder", { fg = "#f7f6f3", bg = "#f7f6f3" })
set_hl("TelescopeMatching", { fg = "#cb912f" })
set_hl("TelescopeNormal", { fg = "#45443f", bg = "#f7f6f3" })
set_hl("TelescopePromptCounter", { fg = "#337ea9" })
set_hl("TelescopePromptTitle", { fg = "#337ea9", bg = "#f7f6f3" })
set_hl("Title", { fg = "#337ea9" })
set_hl("Type", { fg = "#33a999" })
set_hl("VertSplit", { fg = "#edece9" })
set_hl("Visual", { bg = "#d1cfcc" })
set_hl("WarningMsg", { fg = "#cb912f" })
set_hl("WinBar", { fg = "#37352f", bg = "#f7f6f3" })
set_hl("WinBarNC", { fg = "#37352f", bg = "#f7f6f3" })
set_hl("WinSeparator", { fg = "#edece9" })
set_js_hl("@constructor", { fg = "#337ea9" })
set_js_hl("@tag", { fg = "#337ea9" })

vim.g.terminal_color_0 = "#dfdedb"
vim.g.terminal_color_1 = "#d44c48"
vim.g.terminal_color_2 = "#448361"
vim.g.terminal_color_3 = "#cb912f"
vim.g.terminal_color_4 = "#337ea9"
vim.g.terminal_color_5 = "#9065b0"
vim.g.terminal_color_6 = "#33a999"
vim.g.terminal_color_7 = "#c4c3c0"

vim.g.terminal_color_8 = "#dfdedb"
vim.g.terminal_color_9 = "#d44c48"
vim.g.terminal_color_10 = "#448361"
vim.g.terminal_color_11 = "#cb912f"
vim.g.terminal_color_12 = "#337ea9"
vim.g.terminal_color_13 = "#9065b0"
vim.g.terminal_color_14 = "#33a999"
vim.g.terminal_color_15 = "#c4c3c0"